"""Flask app factory for the HOLDFAST web app."""
import os
from pathlib import Path

from flask import Flask, redirect, request, url_for
from flask_login import LoginManager, current_user

from app.models import (
    Attempt,
    ComboBadgeProgress,
    Event,
    SkillGoal,
    SkillProgress,
    User,
    db,
)

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"


def _resolve_database_uri(data_dir: Path, db_path: Path = None) -> str:
    """Postgres (via DATABASE_URL - see render.yaml, which provisions a
    real managed Postgres instance and wires this env var automatically)
    when available, local SQLite file otherwise. Render/Heroku-style
    platforms hand out `postgres://...` URLs, but SQLAlchemy 1.4+ requires
    the `postgresql://` scheme - rewritten here so the raw platform value
    can be used as-is without a manual fixup step.
    """
    database_url = os.environ.get("DATABASE_URL")
    if database_url:
        if database_url.startswith("postgres://"):
            database_url = database_url.replace("postgres://", "postgresql://", 1)
        return database_url
    db_file = db_path or (data_dir / "app.db")
    return f"sqlite:///{db_file}"


def migrate_legacy_data_to(user: User) -> None:
    """One-time carry-forward of data that existed before real accounts
    did: this app used to be a single-local-profile tool (AthleteProfile
    id was hardcoded to 1, and SkillProgress/ComboBadgeProgress/Attempt/
    SkillGoal/Event had no owner at all). Called once, right after the
    very first User account is ever created (see app/auth.py's signup) -
    every legacy row with no owner becomes this user's, so nothing from
    before this change ships is lost.

    Safe to call even if there's no legacy data (a fresh install/fresh
    Postgres instance) - every step is a no-op in that case.

    Note on AthleteProfile specifically: its id IS the owning user's id
    (one-to-one FK, not a separate user_id column). A legacy pre-accounts
    profile row already has id=1 in the database, and this is only ever
    called for the very first User ever created - which gets id=1 on a
    fresh `user` table by the same autoincrement logic. So the legacy
    profile row is automatically "this user's profile" the moment it's
    looked up (see profile_routes.py's _get_or_create_profile) - no
    explicit migration step needed for it.
    """
    for model in (SkillProgress, ComboBadgeProgress, Attempt, SkillGoal, Event):
        model.query.filter_by(user_id=None).update({"user_id": user.id})
    db.session.commit()


def create_app(db_path: Path = None, data_dir: Path = None) -> Flask:
    app = Flask(__name__)

    data_dir = Path(data_dir) if data_dir else DATA_DIR
    app.config["SQLALCHEMY_DATABASE_URI"] = _resolve_database_uri(data_dir, db_path)
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    app.config["MAX_CONTENT_LENGTH"] = 500 * 1024 * 1024  # 500 MB - generous for phone video clips
    # Secret key backs both flash messages and the login session cookie -
    # in production this MUST come from a real env var (see render.yaml's
    # SECRET_KEY, generated by Render itself via generateValue) rather than
    # a hardcoded dev default, or session/auth cookies could be forged.
    app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", "dev-only-insecure-key-do-not-use-in-production")
    app.config["DATA_DIR"] = data_dir

    data_dir.mkdir(parents=True, exist_ok=True)
    (data_dir / "raw_videos").mkdir(parents=True, exist_ok=True)
    (data_dir / "debug_overlays").mkdir(parents=True, exist_ok=True)
    (data_dir / "pose_output").mkdir(parents=True, exist_ok=True)

    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.login_message = "Please log in to continue."
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        return db.session.get(User, int(user_id))

    from app.auth import bp as auth_bp
    from app.routes import bp as routes_bp
    from app.profile_routes import bp as profile_bp
    from app.goals_routes import bp as goals_bp
    from app.friends_routes import bp as friends_bp

    app.register_blueprint(auth_bp)
    app.register_blueprint(routes_bp)
    app.register_blueprint(profile_bp)
    app.register_blueprint(goals_bp)
    app.register_blueprint(friends_bp)

    # Every screen except auth itself requires a real logged-in account -
    # every athlete's data is now owned by a User, so there's no
    # meaningful "logged out" version of any of these routes to show.
    _protected_blueprints = {"main", "profile", "goals", "friends"}

    @app.before_request
    def require_login():
        if request.blueprint in _protected_blueprints and not current_user.is_authenticated:
            return redirect(url_for("auth.login"))

    @app.template_filter("score_tier")
    def score_tier(score) -> str:
        """Buckets a 0-100 score into a semantic tier used for coloring."""
        if score is None:
            return "unknown"
        if score >= 85:
            return "high"
        if score >= 60:
            return "mid"
        return "low"

    @app.template_global("merge_query")
    def merge_query(**overrides):
        """Returns the current request's query params merged with
        `overrides` (a value of None removes that key) - lets History's
        filter/sort/movement links each change one param via url_for while
        preserving whatever else the athlete already has selected, without
        every link needing to know the full current query string.
        """
        params = request.args.to_dict()
        for key, value in overrides.items():
            if value is None:
                params.pop(key, None)
            else:
                params[key] = value
        return params

    with app.app_context():
        db.create_all()
        _ensure_new_columns()

    return app


def _ensure_new_columns() -> None:
    """db.create_all() only creates missing TABLES, never adds columns to a
    table that already exists - so a brand-new column on an existing model
    (like Attempt.is_ranked_clip, added for the Ranked Clip/Profile Rank
    feature) silently never appears on a pre-existing database, whether
    that's a developer's local SQLite file or the real production Postgres
    instance. Patches that gap generically: for each (table, column, DDL)
    below, add the column if it isn't already there. Safe to run on every
    startup - the existence check makes it a no-op once the column exists.
    """
    from sqlalchemy import inspect, text

    column_migrations = [
        ("attempt", "is_ranked_clip", "ALTER TABLE attempt ADD COLUMN is_ranked_clip BOOLEAN NOT NULL DEFAULT FALSE"),
    ]

    inspector = inspect(db.engine)
    existing_tables = set(inspector.get_table_names())
    for table, column, ddl in column_migrations:
        if table not in existing_tables:
            continue  # a fresh db.create_all() above already created it with every current column
        existing_columns = {c["name"] for c in inspector.get_columns(table)}
        if column not in existing_columns:
            with db.engine.begin() as conn:
                conn.execute(text(ddl))
